- name: testyPlaybook
  hosts: win
  tasks:
  - name: Example from an Ansible Playbook
    ansible.windows.win_ping:

- name: Create a text file on the desktop with content
  hosts: win
  tasks:
  - name: Create a text file with content
    ansible.windows.win_copy:
      content: "Hello, this is a sample text."
      dest: 'C:\\Users\\{{ ansible_user }}\\Desktop\\example.txt'


- name: ubuntuSettings
  hosts: ubuntu
  tasks:
  - name: Display message
    debug:
      msg: "Hello Ubuntu"

