---
- name: Ping Redhat Hosts
  hosts: redhat
  tasks:
    - name: Ping Redhat host
      ansible.builtin.ping:
      ignore_unreachable: yes
      ignore_errors: yes

- name: Clear Host Errors after Redhat
  hosts: all
  tasks:
    - meta: clear_host_errors

- name: Ping Ubuntu Hosts
  hosts: ubuntu24
  become: true
  become_method: sudo
  tasks:
    - name: Ping Ubuntu host
      ansible.builtin.ping:
      ignore_unreachable: yes
      ignore_errors: yes

- name: Clear Host Errors after Ubuntu
  hosts: all
  tasks:
    - meta: clear_host_errors

- name: Ping Windows Hosts
  hosts: win
  tasks:
    - name: Ping Windows host
      win_ping:
      ignore_unreachable: yes
      ignore_errors: yes

