---
- name: Copy files from Windows to Ansible controller
  hosts: windows
  vars:
    ansible_controller_ip: "your_ansible_controller_ip"
  tasks:
    - name: Ensure the destination directory exists
      ansible.windows.win_shell:
        _raw_params: "if (!(Test-Path -Path 'C:\\Users\\ansible\\Desktop')) { New-Item -ItemType Directory -Path 'C:\\Users\\ansible\\Desktop' }"

    - name: Check if the file exists
      ansible.windows.win_shell:
        _raw_params: "Test-Path -Path 'C:\\Users\\ansible\\Desktop\\service_info.yaml'"
      register: file_exists

    - name: Debug file existence
      ansible.builtin.debug:
        msg: "File exists: {{ file_exists.stdout }}"

    - name: Ensure destination directory on Ansible controller exists
      ansible.builtin.file:
        path: /root/ansible
        state: directory
      delegate_to: localhost

    - name: Copy files from Windows to the destination directory on Ansible controller using PowerShell
      ansible.windows.win_shell:
        _raw_params: "Copy-Item -Path 'C:\\Users\\ansible\\Desktop\\service_info.yaml' -Destination '\\{{ ansible_controller_ip }}\\root\\ansible\\'"
      when: file_exists.stdout == "True"

