---
- name: Search-only, return list of found updates (if any), log to C:\ansible_wu.txt
  hosts: win
  tasks: 
    - name: Search for Updates
      ansible.windows.win_updates:
        category_names: SecurityUpdates
        state: searched
        log_path: C:\ansible_wu.txt

