- name: Use set_fact with a conditional
  hosts: localhost
  vars:
    user: "admin"
  tasks:
    - name: Set greeting based on user
      set_fact:
        greeting: "Hello, Admin!"
      when: user == "admin"

    - name: Show greeting
      debug:
        msg: "{{ greeting | default('No greeting set') }}"

