---
- name: using a variable include file
  hosts: rhel
  vars_files: myvars.yaml
  tasks:
  - name: install package
    yum:
      name: "{{ item }}"
      state: latest
    loop: "{{ packages }}"
  - name: start and enable service
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop: "{{ packages }}"

